---
author: Jian Shun
date: "2022-09-19"
description: ""
draft: false
#github_link: https://github.com/gurusabarish/hugo-profile
image: /images/global warming.jpeg
tags:
- Visualistion
- Political
- Brexit
title: Global Warming (Temperature Deviations)
toc: null
output:
  html_document:
    theme: flatly
    highlight: zenburn
    number_sections: yes
    toc: yes
    toc_float: yes
    code_folding: show
editor_options: 
  markdown: 
    wrap: 72
---



<div id="climate-change-and-temperature-anomalies" class="section level1">
<h1>Climate change and temperature anomalies</h1>
<p>In this example, we draw upon data from the <em>Combined Land-Surface Air
and Sea-Surface Water Temperature Anomalies</em> in the Northern Hemisphere
at <a href="https://data.giss.nasa.gov/gistemp">NASA’s Goddard Institute for Space
Studies</a>.</p>
<p>For this study, I use the base period of 1951-1980, as stipulated by
NASA - this is the reference period from which we define temperature
anomalies.</p>
<pre class="r"><code>weather &lt;- 
  read_csv(&quot;https://data.giss.nasa.gov/gistemp/tabledata_v4/NH.Ts+dSST.csv&quot;, 
           skip = 1, 
           na = &quot;***&quot;)</code></pre>
<div id="data-manipulation" class="section level2">
<h2>Data Manipulation</h2>
<pre class="r"><code># Create tidyweather data
tidyweather &lt;- weather %&gt;% 
  select(-c(&quot;J-D&quot;, &quot;D-N&quot;, &quot;DJF&quot;, &quot;JJA&quot;, &quot;MAM&quot;, &quot;SON&quot;)) %&gt;% 
  pivot_longer(cols = -Year, names_to = &quot;month&quot;, values_to = &quot;delta&quot;)</code></pre>
</div>
<div id="plotting-scatterplot-of-anomalies-and-trendline" class="section level2">
<h2>Plotting scatterplot of anomalies and trendline</h2>
<pre class="r"><code># Set date format tidyweather data
tidyweather &lt;- tidyweather %&gt;%
  mutate(date = ymd(paste(as.character(Year), month, &quot;1&quot;)),
         month = month(date, label=TRUE),
         year = year(date))

# Plot weather anomalies
ggplot(tidyweather, aes(x=date, y = delta))+
  geom_point()+
  geom_smooth(color=&quot;red&quot;) +
  theme_bw() +
  labs (
    title = &quot;Weather Anomalies&quot;
  )</code></pre>
<p><img src="/blogs/Global_warming_files/figure-html/scatter_plot-1.png" width="648" style="display: block; margin: auto;" /></p>
<p><u><strong>Observation:</strong></u></p>
<p>The effect of increasing temperature is more pronounced in the winter
months - starting from the end of fall until the start of spring. We see
this from the higher values within the winter months over the other
months across time. This reflects the effects of global warming/climate
change throughout the last decade.</p>
<p><img src="/blogs/Global_warming_files/figure-html/facet_wrap-1.png" width="648" style="display: block; margin: auto;" /></p>
</div>
<div id="creating-time-intervals" class="section level2">
<h2>Creating time intervals</h2>
<p>I now create time intervals 30 years apart to make comparisons across
time.</p>
<pre class="r"><code># Assign periods
comparison &lt;- tidyweather %&gt;% 
  filter(Year&gt;= 1881) %&gt;%     #remove years prior to 1881
  #create new variable &#39;interval&#39;, and assign values based on criteria below:
  mutate(interval = case_when(
    Year %in% c(1881:1920) ~ &quot;1881-1920&quot;,
    Year %in% c(1921:1950) ~ &quot;1921-1950&quot;,
    Year %in% c(1951:1980) ~ &quot;1951-1980&quot;,
    Year %in% c(1981:2010) ~ &quot;1981-2010&quot;,
    TRUE ~ &quot;2011-present&quot;
  ))</code></pre>
</div>
<div id="plot-density-plots-of-temperature-anomalies-visualised-across-intervals" class="section level2">
<h2>Plot density plots of temperature anomalies visualised across intervals</h2>
<pre class="r"><code># Create density plot of monthly deviation based off each interval period
ggplot(comparison, aes(delta, fill = interval, alpha = 0.1)) +
  geom_density() +
  labs(title = &quot;Denisty plots of monthly deviations&quot;, subtitle = &quot;Separated by Intervals&quot;, x = &quot;Delta&quot;, y = &quot;Density&quot;) +
  theme(plot.title = element_text(size = 14, hjust = 0.5),
        plot.subtitle = element_text(size = 12, hjust = 0.5),
        axis.title = element_text(size = 12),
        axis.text = element_text(size = 10)
)</code></pre>
<p><img src="/blogs/Global_warming_files/figure-html/density_plot-1.png" width="648" style="display: block; margin: auto;" /></p>
<p><u><strong>Observation:</strong></u></p>
<p>From 1881 until 1980, we did not observe huge anomalies in terms of
temperature delta from the base period (1951-1980). However, this was
not reflected past 1980; temperatures began rising more drastically from
1981-present. More strikingly, the average delta for the last period is
around 0.5 higher than that of the previous period (1981-2010). This
hints at even higher average deviations in future that come faster
unless a downward pressure is exerted on temperature increases through
climate change measures.</p>
</div>
<div id="average-temperature-anomaly-analysis" class="section level2">
<h2>Average temperature anomaly analysis</h2>
<pre class="r"><code># Create yearly averages
average_annual_anomaly &lt;- comparison %&gt;%
  group_by(Year) %&gt;% 
  summarise(mean_delta_year = mean(delta))

# plot mean annual delta across years:
ggplot(average_annual_anomaly, aes(x = Year, y= mean_delta_year)) +
  geom_point() +
  geom_smooth(colour = &quot;red&quot;, method = &quot;loess&quot;) +
  theme_bw() +
  labs (
    title = &quot;Yearly Weather Anomalies&quot;,
    y = &quot;Mean annual delta&quot;
  )</code></pre>
<p><img src="/blogs/Global_warming_files/figure-html/averaging-1.png" width="648" style="display: block; margin: auto;" /></p>
<pre class="r"><code>#Fit the best fit line, using LOESS method
#change theme to theme_bw() to have white background + black frame around plot</code></pre>
<p><u><strong>Observation:</strong></u></p>
<p>Like what we were hinting at earlier, the yearly anomalies over the past
4 decades (starting from 1980) have followed a relatively exponential
upward trend. During the 1980s, the average yearly delta was between 0
and 0.5 whereas this average has climbed past 1.5 in the most recent
years. This increase of 1 degree overall has not been witnessed in the
century prior to 1980, thus emphasising the magnitude of the rapidly
worsening global warming phenomenon.</p>
</div>
<div id="creating-confidence-intervals-for-temperature-anomalies" class="section level2">
<h2>Creating Confidence Intervals for temperature anomalies</h2>
<p>Here, I calculate a 95% confidence interval for temperature anomalies
within the time period from 2011 to present.</p>
<pre class="r"><code># Formula method of CI calculation
formula_ci &lt;- comparison %&gt;%
  filter(interval == &quot;2011-present&quot;) %&gt;%
  drop_na() %&gt;% 
  summarise(mean_delta = mean(delta),
                     sd_delta = sd(delta),
                     count = n(),
                     t_critical = qt(0.975, count-1),
                     se_delta = sd_delta / sqrt(count),
                     margin_of_error = t_critical * se_delta,
                     delta_low  = mean_delta - margin_of_error,
                     delta_high  = mean_delta + margin_of_error
            )
# Print out formula_CI
formula_ci</code></pre>
<pre><code>## # A tibble: 1 × 8
##   mean_delta sd_delta count t_critical se_delta margin_of_error delta_…¹ delta…²
##        &lt;dbl&gt;    &lt;dbl&gt; &lt;int&gt;      &lt;dbl&gt;    &lt;dbl&gt;           &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;
## 1       1.07    0.266   139       1.98   0.0226          0.0446     1.02    1.11
## # … with abbreviated variable names ¹​delta_low, ²​delta_high</code></pre>
<pre class="r"><code>library(infer)
# Bootstrap method of CI calculation using Infer package
infer_bootstrap_ci &lt;- comparison %&gt;%
  filter(interval == &quot;2011-present&quot;) %&gt;%
  specify(response = delta) %&gt;%
  generate(reps = 1000,  type = &quot;bootstrap&quot;) %&gt;% 
  calculate(stat = &quot;mean&quot;, na.rm = TRUE) %&gt;% 
  get_confidence_interval(level = .95)
# Print out bootstrap CI using Infer package
infer_bootstrap_ci</code></pre>
<pre><code>## # A tibble: 1 × 2
##   lower_ci upper_ci
##      &lt;dbl&gt;    &lt;dbl&gt;
## 1     1.02     1.11</code></pre>
<p><u><strong>Analysis:</strong></u></p>
<p>The results give an interesting insight into the sea and land
temperature differences during the 2011 - present time interval. The
mean of the temperature delta is around 1.06 degrees. By means of a
confidence interval calculation we can state with 95% certainty that the
mean temperature delta is between 1.02 and 1.11 degrees for this time
period. As there is no underlying distribution, we used the t-statistics
and a degrees of freedom of n-1 to calculate the critical values
required for a confidence interval calculation. We confirmed this
estimate by using a bootstrapping method that manually created the
confidence intervals and provided a lower bound of 1.02 degrees and a
upper bound of 1.11 degrees.</p>
</div>
</div>
